In [3]:
import numpy as np

In [6]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [7]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

## How many negative numbers are there?

In [8]:
a[a < 0]

array([-2, -1, -6, -7])

In [26]:
len(a[a < 0])

4

## How many positive numbers are there?

In [9]:
a[a > 0]

array([ 4, 10, 12, 23,  3])

In [27]:
len(a[a > 0])

5

## How many even positive numbers are there?

In [18]:
a[(a > 0) & (a % 2 == 0)] #don't forget the parentheses

array([ 4, 10, 12])

In [28]:
len(a[(a > 0) & (a % 2 == 0)])

3

## If you were to add 3 to each data point, how many positive numbers would there be?

In [12]:
b = a + 3

In [13]:
b

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [14]:
b[b > 0]

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

In [29]:
len(b[b > 0])

10

## If you squared each number what would the new mean and standard deviation be?

In [15]:
sq = a ** 2

In [17]:
sq.mean()

74.0

In [16]:
sq.std()

144.0243035046516

## Centering

In [20]:
c = a - a.mean()

In [21]:
c

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [22]:
a.mean()

3.0

## Z-Score

In [24]:
z = (a - a.mean())/a.std()

In [25]:
z

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

## More Numpy Practice

Setup #1

import numpy as np

In [30]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Exercise 1

In [35]:
sum_of_a = 0
for _ in a:
    sum_of_a += int(_)

sum_of_a

55

Exercise 2

In [36]:
min_of_a = float('inf')
for _ in a:
    if _ < min_of_a:
        min_of_a = _
min_of_a

1

Exercise 3

In [37]:
max_of_a = float('-inf')
for _ in a:
    if _ > max_of_a:
        max_of_a = _
max_of_a

10

Exercise 4

In [47]:
mean_of_a = 0
for _ in a:
    mean_of_a += _
mean_of_a = mean_of_a / len(a)

mean_of_a

5.5

Exercise 5

In [48]:
product_of_a = 1
for _ in a:
    product_of_a *= _
    
product_of_a

3628800

Exercise 6

In [41]:
squares_of_a = [_ * _ for _ in a]
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [43]:
odds_in_a = [_ for _ in a if _ % 2 == 1]
odds_in_a

[1, 3, 5, 7, 9]

In [45]:
evens_in_a = [_ for _ in a if _ % 2 == 0]
evens_in_a

[2, 4, 6, 8, 10]

Setup #2

In [83]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

Exercise 1

In [84]:
b = np.array(b)
b

array([[3, 4, 5],
       [6, 7, 8]])

In [66]:
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
sum_of_b

33

In [67]:
b.sum()

33

Exercise 2

In [74]:
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])
min_of_b

3

In [78]:
b.min()

3

Exercise 3

In [77]:
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
max_of_b

8

In [79]:
b.max()

8

Exercise 4

In [86]:
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
mean_of_b

5.5

In [85]:
b.mean()

5.5

Exercise 5

In [88]:
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
product_of_b

20160

In [89]:
b.prod()

20160

Exercise 6

In [92]:
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number ** 2)
squares_of_b

[9, 16, 25, 36, 49, 64]

In [96]:
b_sq = b ** 2
b_sq

array([[ 9, 16, 25],
       [36, 49, 64]])

Exercise 7

In [97]:
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
odds_in_b

[3, 5, 7]

In [98]:
b[b % 2 == 1]

array([3, 5, 7])

Exercise 8

In [101]:
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
evens_in_b

[4, 6, 8]

In [102]:
b[b % 2 == 0]

array([4, 6, 8])

Exercise 9

In [104]:
print(b.shape)

(2, 3)


Exercise 10

In [105]:
b.transpose() #Regular Python method

array([[3, 6],
       [4, 7],
       [5, 8]])

In [180]:
np.transpose(b) #from numpy function?

array([[3, 6],
       [4, 7],
       [5, 8]])

Exercise 11

In [111]:
np.reshape(b, (1, 6))

array([[3, 4, 5, 6, 7, 8]])

In [112]:
np.reshape(b, -1)

array([3, 4, 5, 6, 7, 8])

Exercise 12

In [114]:
np.reshape(b, (6 ,1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

Setup #3

In [115]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [116]:
c = np.array(c)

Exercise 1

In [125]:
print(f'The min is {c.min()}')
print(f'The max is {c.max()}')
print(f'The sum is {c.sum()}')
print(f'The product is {c.prod()}')


The min is 1
The max is 9
The sum is 45
The product is 362880


Exercise 2

In [126]:
c.std()

2.581988897471611

Exercise 3

In [129]:
c.var()

6.666666666666667

Exercise 4

In [128]:
print(c.shape)

(3, 3)

In [184]:
print(np.shape(c))

(3, 3)


Exercise 5

In [136]:
print(np.transpose(c)) #OR

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [145]:
print(c.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


Exercise 6

In [143]:
np.dot(c, c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

Exercise 7

In [159]:
c_ct = c * np.transpose(c)
c_ct.sum()
# sum(c_ct)
# c_ct

261

Exercise 8

In [161]:
c_ct.prod()

131681894400

Setup #4

In [163]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [166]:
d = np.array(d)

In [167]:
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

Exercise 1

In [170]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

Exercise 2

In [175]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

Exercise 3

In [176]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

Exercise 4

In [177]:
d[d < 0]

array([-90, -30, -45, -45])

Exercise 5

In [178]:
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

Exercise 6

In [179]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

Exercise 7

In [181]:
len(np.unique(d))

11

Exercise 8

In [182]:
d.shape

(3, 6)

In [183]:
np.shape(d)

(3, 6)

Exercise 9

In [189]:
print(np.shape(np.transpose(d)))

(6, 3)


Exercise 10

In [190]:
np.reshape(d, (9,2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])